name: Build and Export with Custom Godot

on:
  workflow_dispatch:

jobs:
  build_and_export:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies for building Godot
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential scons pkg-config python3 python3-pip libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libfreetype6-dev libssl-dev libudev-dev libxrandr-dev libxi-dev

      # Step 3: Clone the Godot source code
      - name: Clone Godot source
        run: |
          git clone https://github.com/godotengine/godot.git
          cd godot
          git checkout 4.4.1-stable

      # Step 4: Compile Godot with debug symbols
      - name: Compile Godot
        run: |
          cd godot
          scons platform=linuxbsd target=template_debug debug_symbols=true -j$(nproc)

      - name: Check folder contents
        run: |
          cd bin
          ls -l

      # Step 5: Export the project using the compiled Godot binary
      - name: Export project
        run: |
          ./godot/bin/godot.linux.editor.x86_64.console --headless --export-debug --verbose "Windows Desktop"

      # Step 6: Upload the exported build as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: exported-build
          path: export/